services:
  postgres:
    image: postgres:15
    container_name: kiosk-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kiosk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/KioskAPI
      dockerfile: Dockerfile
    container_name: kiosk-backend
    ports:
      - "5226:5226"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5226
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=kiosk;Username=admin;Password=admin
    depends_on:
      - postgres

  agent:
    build:
      context: ../agent/KioskAgent
      dockerfile: Dockerfile
    container_name: kiosk-agent
    depends_on:
      - backend
    environment:
      - Backend__BaseUrl=http://backend:5226

  frontend:
    build:
      context: ../frontend/kiosk-ui
      dockerfile: Dockerfile
    container_name: kiosk-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
